### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by kzys**
*Issue #, if available:*

*Description of changes:*

The first commit simplifies Makefile. The second commit adds a YAML for GitHub Actions.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by JoseVillalta — APPROVED** [review]
LGTM

**Comment by kzys** [comment]
You can see the result of GitHub Actions on https://github.com/kzys/amazon-ecs-shim-loggers-for-containerd/actions/runs/1183770258.

**Review by aarongoulet — APPROVED** [review]
Looks good!

**Review by akshat-kmr — APPROVED** [review]
Really cool!

**Review by aaithal — APPROVED** [review]
thanks for doing this!

**Pull request merged**
